name: Manualy build the repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: yarn install

      - name: build
        run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: banner-card.js
          path: banner-card.js
